services:

  client:
    container_name: client
    build: ./client
    ports:
      - "80:80"
    restart: always
  
  server:
    container_name: server
    build: ./server
    env_file: ./server/.env
    volumes:
      - db:/server
    ports:
      - "4001:4001"
    restart: always

volumes:
  db: